substitutions:
  device_name: "flexispot-e7"
  friendly_name: "Flexispot E7"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source:
      type: local
      path: components

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:
  - platform: esphome

logger:
  baud_rate: 0  # Disabled - UART pins are used for desk
  logs:
    desk_height: DEBUG

uart:
  id: desk_uart
  baud_rate: 9600
  tx_pin: GPIO1   # Green wire
  rx_pin: GPIO3   # White/Blue wire
  rx_buffer_size: 256

sensor:
  - platform: desk_height
    id: desk_height_sensor
    name: "Desk Height"
    uart_id: desk_uart
    unit_of_measurement: "cm"
    accuracy_decimals: 1
    device_class: distance
    state_class: measurement
    icon: "mdi:desk"
    filters:
      - filter_out: 0.0

  - platform: wifi_signal
    name: "WiFi RSSI"
    update_interval: 60s

switch:
  - platform: gpio
    id: virtual_screen
    pin:
      number: GPIO21  # Blue wire
      mode: OUTPUT
    restore_mode: ALWAYS_ON
    internal: true

button:
  - platform: uart
    name: "Preset 1"
    id: preset_1
    icon: "mdi:numeric-1-box"
    uart_id: desk_uart
    data: [0x9b, 0x06, 0x02, 0x04, 0x00, 0xac, 0xa3, 0x9d]

  - platform: uart
    name: "Preset 2"
    id: preset_2
    icon: "mdi:numeric-2-box"
    uart_id: desk_uart
    data: [0x9b, 0x06, 0x02, 0x08, 0x00, 0xac, 0xa6, 0x9d]

  - platform: uart
    name: "Sit"
    id: preset_sit
    icon: "mdi:chair-rolling"
    uart_id: desk_uart
    data: [0x9b, 0x06, 0x02, 0x00, 0x01, 0xac, 0x60, 0x9d]

  - platform: uart
    name: "Stand"
    id: preset_stand
    icon: "mdi:human-handsup"
    uart_id: desk_uart
    data: [0x9b, 0x06, 0x02, 0x10, 0x00, 0xac, 0xac, 0x9d]

  - platform: uart
    name: "Up"
    id: button_up
    uart_id: desk_uart
    data: [0x9b, 0x06, 0x02, 0x01, 0x00, 0xfc, 0xa0, 0x9d]
    internal: true

  - platform: uart
    name: "Down"
    id: button_down
    uart_id: desk_uart
    data: [0x9b, 0x06, 0x02, 0x02, 0x00, 0x0c, 0xa0, 0x9d]
    internal: true

  - platform: uart
    name: "Memory (M)"
    id: button_memory
    icon: "mdi:alpha-m-circle"
    uart_id: desk_uart
    data: [0x9b, 0x06, 0x02, 0x20, 0x00, 0xac, 0xb8, 0x9d]

  - platform: restart
    name: "Reboot ESP"
    icon: "mdi:restart"
